#
# Configure a cluster of 3 consul servers
#
- hosts: consul_servers
  become_user: root
  become: true
  become_method: sudo

  pre_tasks:
    - name: setup hosts file so the servers can ref one another by hostname
      lineinfile: "dest=/etc/hosts state=present regexp='^{{item.ip}}' insertafter='^127.0.0.1' line='{{item.ip}} {{item.hostname}}'"
      with_items:
        - {ip: '11.0.0.2', hostname: 'consul-1'}
        - {ip: '11.0.0.3', hostname: 'consul-2'}
        - {ip: '11.0.0.4', hostname: 'consul-3'}


  roles:
    - {role: sgargan.supervisor }
    - {role: sgargan.consul,
        consul_server: true,
        consul_supervisor_enabled: true,
        consul_node_name: "{{inventory_hostname}}",
        consul_join: '{{groups["consul_servers"]}}',
        # use the second interface for vbox as the first is a nat address
        consul_interface: '{{hostvars[inventory_hostname]["ansible_eth1"]["ipv4"]["address"]}}',
        consul_client_address: '0.0.0.0'}

# install an agent locally that will join the 3 node server cluster.
#- hosts: localhost
#  connection: local
#
#  roles:
#
#    - {role: sgargan.consul,
#        consul_supervisor_enabled: true,
#        consul_dir: "{{local_agent_dir}}",
#        consul_node_name: "{{ansible_hostname}}",
#        consul_join: ['11.0.0.2', '11.0.0.3', '11.0.0.4'],
#        consul_client_address: '0.0.0.0'}
